name: Build and deploy Python app to Azure Web App - CROPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python version
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Zip the application
      - name: Create deployment package
        run: |
          powershell Compress-Archive -Path * -DestinationPath release.zip -Force

      # Step 5: Deploy to Azure Web App using Publish Profile
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CROPS'
          publish-profile: ${{ secrets.my_secret_2 }}
          package: release.zip
